import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Zen Pro
 */
public class DodajClan extends javax.swing.JInternalFrame {

    /**
     * Creates new form DodajClan
     */
  ConnectionBase _db = new ConnectionBase();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public DodajClan() {
        initComponents();
        
        tabela();
        autoid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dodajBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        obrisiBtn = new javax.swing.JButton();
        clanTxt = new javax.swing.JTextField();
        imeTxt = new javax.swing.JTextField();
        prezimeTxt = new javax.swing.JTextField();
        polJcb = new javax.swing.JComboBox<>();
        tipJcb = new javax.swing.JComboBox<>();
        telTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabelaPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(990, 530));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dodajBtn.setBackground(new java.awt.Color(255, 255, 255));
        dodajBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dodajBtn.setText("Dodaj");
        dodajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dodajBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 80, 30));

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, 30));

        obrisiBtn.setBackground(new java.awt.Color(255, 255, 255));
        obrisiBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        obrisiBtn.setText("Obrisi");
        obrisiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBtnActionPerformed(evt);
            }
        });
        jPanel1.add(obrisiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 80, 30));

        clanTxt.setEditable(false);
        clanTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clanTxtActionPerformed(evt);
            }
        });
        jPanel1.add(clanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 40));

        imeTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        imeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(imeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, 30));

        prezimeTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prezimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezimeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(prezimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 250, 30));

        polJcb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        polJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZABERITE POL", "M", "Z" }));
        jPanel1.add(polJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 250, 30));

        tipJcb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tipJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZBARITE TIP", "STUDENT", "DRUGO" }));
        jPanel1.add(tipJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 250, 30));

        telTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(telTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 250, 30));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 250, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Clan ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Ime");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Prezime");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Pol");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Tip Clana");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 100, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Broj Telefona");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel3.setText("Clanovi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 920, 50));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelaPane.setViewportView(tabela);

        jPanel1.add(tabelaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 940, 200));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 960, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clanTxtActionPerformed

    private void imeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeTxtActionPerformed

    private void prezimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prezimeTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String clanid = clanTxt.getText();
        String ime = imeTxt.getText();
        String prezime = prezimeTxt.getText();
        String pol = polJcb.getSelectedItem().toString();
        String email = emailTxt.getText();
        String brojtel = telTxt.getText();
        String tip = tipJcb.getSelectedItem().toString();
        
        try {
           con = _db.ConnectBase();
            String sql="UPDATE `dodajclan` SET `ime`='"+ime+"',`prezime`='"+prezime+"',`pol`='"+pol+"',`email`='"+email+"',`brojtel`='"+brojtel+"',`tip`='"+tip+"' WHERE `cid`='"+clanid+"'";
           pst =  con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste updateovali!");
            tabela();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void dodajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBtnActionPerformed
        // TODO add your handling code here:
        String clanid = clanTxt.getText();
        String ime = imeTxt.getText();
        String prezime = prezimeTxt.getText();
        String pol = polJcb.getSelectedItem().toString();
        String email = emailTxt.getText();
        String brojtel = telTxt.getText();
        String tip = tipJcb.getSelectedItem().toString();
        
        
        try {
           con = _db.ConnectBase();
            String sql="INSERT INTO `dodajclan`(`cid`, `ime`, `prezime`, `pol`, `email`, `brojtel`, `tip`) VALUES ('"+clanid+"','"+ime+"','"+prezime+"','"+pol+"','"+email+"','"+brojtel+"','"+tip+"')";
            pst =  con.prepareStatement(sql);
            pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste uneli!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        clear();
        tabela();
        autoid();
        
    
    }//GEN-LAST:event_dodajBtnActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmod = (DefaultTableModel) tabela.getModel();
        int redid = tabela.getSelectedRow();
        
        clanTxt.setText(tmod.getValueAt(redid, 0).toString());
        imeTxt.setText(tmod.getValueAt(redid, 1).toString());
        prezimeTxt.setText(tmod.getValueAt(redid, 2).toString());
        polJcb.setSelectedItem(tmod.getValueAt(redid, 3).toString());
        emailTxt.setText(tmod.getValueAt(redid, 4).toString());
        telTxt.setText(tmod.getValueAt(redid, 5).toString());
        tipJcb.setSelectedItem(tmod.getValueAt(redid, 6).toString());
 
    }//GEN-LAST:event_tabelaMouseClicked

    private void obrisiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBtnActionPerformed
        // TODO add your handling code here:
        try{ 
        con = _db.ConnectBase();
            String sql="DELETE FROM `dodajclan` WHERE cid = '"+clanTxt.getText()+"'";
           pst =  con.prepareStatement(sql);
            pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali!");
                tabela();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_obrisiBtnActionPerformed

    private void autoid()
    {
        try {
            con = _db.ConnectBase();
            String sql = "SELECT `cid` FROM `dodajclan` ORDER BY cid DESC LIMIT 1 ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
           if(rs.next())
           {
               String rb = rs.getString("cid");
               int rac = rb.length();
               String t = rb.substring(0, 2);
               String b = rb.substring(2, rac);
               int br = Integer.parseInt(b);
               br++;
               String sb = Integer.toString(br);
               String txt = t+sb;
               clanTxt.setText(txt);
               
           }
           else
           {
               clanTxt.setText("DC0000");
           }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
    }
    private void tabela()
    {
        try{
            con = _db.ConnectBase();
            String sql = "SELECT `cid`, `ime`, `prezime`, `pol`, `email`, `brojtel`, `tip` FROM `dodajclan` ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tabela.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    private void clear()
    {
        clanTxt.setText("");
        imeTxt.setText("");
        prezimeTxt.setText("");
        polJcb.setSelectedIndex(0);
        emailTxt.setText("");
        telTxt.setText("");
       tipJcb.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clanTxt;
    private javax.swing.JButton dodajBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField imeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton obrisiBtn;
    private javax.swing.JComboBox<String> polJcb;
    private javax.swing.JTextField prezimeTxt;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaPane;
    private javax.swing.JTextField telTxt;
    private javax.swing.JComboBox<String> tipJcb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
