import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zen Pro
 */
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
public class DodajKnjigu extends javax.swing.JInternalFrame {

    /**
     * Creates new form DodajKnjigu
     */
    ConnectionBase _db = new ConnectionBase();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public DodajKnjigu() {
        initComponents();
        
        autoid();
        tabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dodajBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        obrisiBtn = new javax.swing.JButton();
        knjTxt = new javax.swing.JTextField();
        nazivTxt = new javax.swing.JTextField();
        autorTxt = new javax.swing.JTextField();
        katJcb = new javax.swing.JComboBox<>();
        tipKJcb = new javax.swing.JComboBox<>();
        godinaTxt = new javax.swing.JTextField();
        sifraTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cenaTxt = new javax.swing.JTextField();
        tabelaPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(850, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dodajBtn.setBackground(new java.awt.Color(255, 255, 255));
        dodajBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dodajBtn.setText("Dodaj");
        dodajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dodajBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 80, 30));

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 30));

        obrisiBtn.setBackground(new java.awt.Color(255, 255, 255));
        obrisiBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        obrisiBtn.setText("Obrisi");
        obrisiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(obrisiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 80, 30));

        knjTxt.setEditable(false);
        knjTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        knjTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knjTxtActionPerformed(evt);
            }
        });
        getContentPane().add(knjTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 40));

        nazivTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nazivTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazivTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nazivTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 250, 30));

        autorTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        autorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTxtActionPerformed(evt);
            }
        });
        getContentPane().add(autorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 250, 30));

        katJcb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        katJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZABERITE KATEGORIJU", "ISTORIJA", "FANTAZIJA", "KOMICNA", "AKCIJA", "HOROR", "DRUGE" }));
        katJcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katJcbActionPerformed(evt);
            }
        });
        getContentPane().add(katJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 250, 30));

        tipKJcb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tipKJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IZBARITE TIP", "POZAJMITI", "CITATI SAMO" }));
        tipKJcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipKJcbActionPerformed(evt);
            }
        });
        getContentPane().add(tipKJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 250, 30));

        godinaTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(godinaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 250, 30));

        sifraTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(sifraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Knjiga ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Naziv");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Autor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 100, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Kategorija");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Sifra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Tip Knjige");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 100, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Godina");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 100, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel3.setText("Knjige");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 920, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Cena");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 100, 40));
        getContentPane().add(cenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 250, 30));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabelaPane.setViewportView(tabela);

        getContentPane().add(tabelaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 940, 200));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 960, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBtnActionPerformed
        // TODO add your handling code here:
        String knjigaid = knjTxt.getText();
        String naziv = nazivTxt.getText();
        String sifra = sifraTxt.getText();
        String kat = katJcb.getSelectedItem().toString();
        String autor = autorTxt.getText();
        String godina = godinaTxt.getText();
        String tip = tipKJcb.getSelectedItem().toString();
        String cena = cenaTxt.getText();

        try {
            con = _db.ConnectBase();
            String sql="INSERT INTO `dodajknjigu`(`kid`, `naziv`, `sifra`, `kategorija`, `autor`, `godina`, `tip`, `cena`,`ozn`) VALUES ('"+knjigaid+"','"+naziv+"','"+sifra+"','"+kat+"','"+autor+"','"+godina+"','"+tip+"','"+cena+"','0')";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste uneli!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        autoid();
         tabela();
        
        clear();

    }//GEN-LAST:event_dodajBtnActionPerformed
 private void tabela()
    {
        try{
            con = _db.ConnectBase();
            String sql = "SELECT `kid`, `naziv`, `sifra`, `kategorija`, `autor`, `godina`, `tip`, cena FROM `dodajknjigu` ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tabela.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    private void autoid()
    {
        try {
            con = _db.ConnectBase();
            String sql = "SELECT `kid` FROM `dodajknjigu` ORDER BY kid DESC LIMIT 1 ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
           if(rs.next())
           {
               String rb = rs.getString("kid");
               int rac = rb.length();
               String t = rb.substring(0, 2);
               String b = rb.substring(2, rac);
               int br = Integer.parseInt(b);
               br++;
               String sb = Integer.toString(br);
               String txt = t+sb;
               knjTxt.setText(txt);
               
           }
           else
           {
               knjTxt.setText("DK0000");
           }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
            
        }
    }
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String knjigaid = knjTxt.getText();
        String naziv = nazivTxt.getText();
        String sifra = sifraTxt.getText();
        String kat = katJcb.getSelectedItem().toString();
        String autor = autorTxt.getText();
        String godina = godinaTxt.getText();
        String tip = tipKJcb.getSelectedItem().toString();
        String cena = cenaTxt.getText();


        try {
            con = _db.ConnectBase();
            String sql="UPDATE `dodajknjigu` SET `naziv`='"+naziv+"',`sifra`='"+sifra+"',`kategorija`='"+kat+"',`autor`='"+autor+"',`godina`='"+godina+"',`tip`='"+tip+"',`cena`='"+cena+"' WHERE `kid`='"+knjigaid+"'";
             pst =  con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste updateovali!");
            tabela();
            clear();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }autoid();
    }//GEN-LAST:event_updateBtnActionPerformed

        private void clear()
    {
        knjTxt.setText("");
        nazivTxt.setText("");
        sifraTxt.setText("");
        katJcb.setSelectedIndex(0);
        autorTxt.setText("");
        godinaTxt.setText("");
        tipKJcb.setSelectedIndex(0);
        cenaTxt.setText("");
    }
        
    private void obrisiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBtnActionPerformed
        // TODO add your handling code here:

        try{
           con = _db.ConnectBase();
            String sql="DELETE FROM `dodajknjigu` WHERE kid = '"+knjTxt.getText()+"'";
            pst =  con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali!");
            tabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }clear();
       
    }//GEN-LAST:event_obrisiBtnActionPerformed

    private void nazivTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazivTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazivTxtActionPerformed

    private void autorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTxtActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmod = (DefaultTableModel) tabela.getModel();
        int redid = tabela.getSelectedRow();

        knjTxt.setText(tmod.getValueAt(redid, 0).toString());
        nazivTxt.setText(tmod.getValueAt(redid, 1).toString());
        sifraTxt.setText(tmod.getValueAt(redid, 2).toString());
        katJcb.setSelectedItem(tmod.getValueAt(redid, 3).toString());
        autorTxt.setText(tmod.getValueAt(redid, 4).toString());
        godinaTxt.setText(tmod.getValueAt(redid, 5).toString());
        tipKJcb.setSelectedItem(tmod.getValueAt(redid, 6).toString());
        cenaTxt.setText(tmod.getValueAt(redid,7).toString());

    }//GEN-LAST:event_tabelaMouseClicked

    private void katJcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katJcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_katJcbActionPerformed

    private void tipKJcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipKJcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipKJcbActionPerformed

    private void knjTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knjTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knjTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorTxt;
    private javax.swing.JTextField cenaTxt;
    private javax.swing.JButton dodajBtn;
    private javax.swing.JTextField godinaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> katJcb;
    private javax.swing.JTextField knjTxt;
    private javax.swing.JTextField nazivTxt;
    private javax.swing.JButton obrisiBtn;
    private javax.swing.JTextField sifraTxt;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaPane;
    private javax.swing.JComboBox<String> tipKJcb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
