
import com.mysql.jdbc.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zen Pro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
       Connection conn=null;
       
    
    public Main() {
        initComponents();
        conn=(Connection) ConnectionBase.ConnectBase();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iznKBtn = new javax.swing.JButton();
        vraKBtn = new javax.swing.JButton();
        dodCBtn = new javax.swing.JButton();
        dodKBtn = new javax.swing.JButton();
        deskPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 675));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iznKBtn.setBackground(new java.awt.Color(255, 255, 255));
        iznKBtn.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        iznKBtn.setText("Iznajmiti Knjigu");
        iznKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iznKBtnActionPerformed(evt);
            }
        });
        jPanel1.add(iznKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));

        vraKBtn.setBackground(new java.awt.Color(255, 255, 255));
        vraKBtn.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        vraKBtn.setText("Vratiti Knjigu");
        vraKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vraKBtnActionPerformed(evt);
            }
        });
        jPanel1.add(vraKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 30));

        dodCBtn.setBackground(new java.awt.Color(255, 255, 255));
        dodCBtn.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        dodCBtn.setText("Dodati Clanove");
        dodCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodCBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dodCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 30));

        dodKBtn.setBackground(new java.awt.Color(255, 255, 255));
        dodKBtn.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        dodKBtn.setText("Dodati Knjige");
        dodKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodKBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dodKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, 30));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        deskPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        jPanel1.add(deskPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 1080, 580));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setText("Biblioteka");

        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("KNJIGE");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE))
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void dodCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodCBtnActionPerformed
        // TODO add your handling code here:
        
        deskPane.removeAll();
        DodajClan dc = new DodajClan();
        deskPane.add(dc).setVisible(true);
        
    }//GEN-LAST:event_dodCBtnActionPerformed

    private void iznKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iznKBtnActionPerformed
        // TODO add your handling code here:
        deskPane.removeAll();
        IznajmitiKnjigu ik = new IznajmitiKnjigu();
        deskPane.add(ik).setVisible(true);
    }//GEN-LAST:event_iznKBtnActionPerformed

    private void vraKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vraKBtnActionPerformed
        // TODO add your handling code here:
        deskPane.removeAll();
        VratitKnjigu vk = new VratitKnjigu(); 
        deskPane.add(vk).setVisible(true);
    }//GEN-LAST:event_vraKBtnActionPerformed

    private void dodKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodKBtnActionPerformed
        // TODO add your handling code here:
        deskPane.removeAll();
        DodajKnjigu vk = new DodajKnjigu();
        deskPane.add(vk).setVisible(true);
    }//GEN-LAST:event_dodKBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        deskPane.removeAll();
        Knjige k = new Knjige();
        deskPane.add(k).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JButton dodCBtn;
    private javax.swing.JButton dodKBtn;
    private javax.swing.JButton iznKBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton vraKBtn;
    // End of variables declaration//GEN-END:variables
}
