import java.awt.print.PrinterException;
import java.lang.System.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zen Pro
 */
public class VratitKnjigu extends javax.swing.JInternalFrame {

    /**
     * Creates new form VratitKnjigu
     */
    
    ConnectionBase _db = new ConnectionBase();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public VratitKnjigu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vratiBtn = new javax.swing.JButton();
        spisakBtn = new javax.swing.JButton();
        knjigaTxt = new javax.swing.JTextField();
        clanTxt = new javax.swing.JTextField();
        zakTxt = new javax.swing.JTextField();
        urTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spisakTxt = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vratiBtn.setBackground(new java.awt.Color(255, 255, 255));
        vratiBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vratiBtn.setText("Vrati");
        vratiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vratiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(vratiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 340, 60));

        spisakBtn.setBackground(new java.awt.Color(255, 255, 255));
        spisakBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        spisakBtn.setText("Spisak");
        spisakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spisakBtnActionPerformed(evt);
            }
        });
        getContentPane().add(spisakBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 340, 60));

        knjigaTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        knjigaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knjigaTxtActionPerformed(evt);
            }
        });
        knjigaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                knjigaTxtKeyReleased(evt);
            }
        });
        getContentPane().add(knjigaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, 40));

        clanTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clanTxtActionPerformed(evt);
            }
        });
        clanTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clanTxtKeyReleased(evt);
            }
        });
        getContentPane().add(clanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, 40));

        zakTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        zakTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakTxtActionPerformed(evt);
            }
        });
        getContentPane().add(zakTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, 30));

        urTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(urTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 250, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Knjiga ID");
        jLabel4.setPreferredSize(new java.awt.Dimension(850, 500));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Zakasnjenje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Uredu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel3.setText("Vratiti Knjigu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 920, 50));

        spisakTxt.setColumns(20);
        spisakTxt.setRows(5);
        getContentPane().add(spisakTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 350, 260));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Clan ID");
        jLabel12.setPreferredSize(new java.awt.Dimension(850, 500));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 730));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 350, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vratiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vratiBtnActionPerformed
         //ovde treba da mi se vracaju podatke odmah cim upisem kid(knjiga id) pokusavala sam dosta upitnika... ako mi vi mozete pomoci malo
        String kid = knjigaTxt.getText();
        String cid = clanTxt.getText();
        String zakdat = zakTxt.getText();
        String ur = urTxt.getText();
        
        try {
           
            String sql="INSERT INTO `vratiknjigu`( `kid`, `cid`, `zakdat`, `ur`) VALUES ('"+kid+"','"+cid+"','"+zakdat+"','"+ur+"')";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.execute();
            update();
            spisak();
            vraozn();
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste uneli!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_vratiBtnActionPerformed
 
     private void spisak()
    {
        spisakTxt.setText("#######################################"+"/n" + "Biblioteka" + "/n" 
                + zakTxt.getText() + "/n" + urTxt.getText() +"/n" + "#######################################");
    
    }
     
     
//      private void update()
//    {
//    try {
//            Class.forName("com.mysql.jdbc.Driver");
//            java.sql.Connection   conn = DriverManager.getConnection("jdbc:mysql://localhost/biblioteka","root",""); 
//            String sql="UPDATE `dodajknjigu` SET `ozn`='0' WHERE kid='"+knjigaTxt.getText()+"'";
//            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
//            pst.execute();
//            //JOptionPane.showMessageDialog(rootPane, "Uspesno ste updateovali!");
//            
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e);
//        }
//    }
      
    
//    private void vraozn()
//    {
//    try {
//            Class.forName("com.mysql.jdbc.Driver");
//            java.sql.Connection   conn = DriverManager.getConnection("jdbc:mysql://localhost/biblioteka","root",""); 
//            String sql="UPDATE `vratiknjigu` SET `ozn`='1' WHERE kid='"+knjigaTxt.getText()+"'";
//            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
//            pst.execute();
//            //JOptionPane.showMessageDialog(rootPane, "Uspesno ste updateovali!");
//            
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e);
//        }
//    }
//    
    
    private void spisakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spisakBtnActionPerformed
        try {
            spisakTxt.print();
        } catch (PrinterException ex) {
            java.util.logging.Logger.getLogger(VratitKnjigu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_spisakBtnActionPerformed

    private void knjigaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knjigaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knjigaTxtActionPerformed

    private void knjigaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_knjigaTxtKeyReleased
        // TODO add your handling code here:
        try {
           
            String sql="SELECT  `cid`,   `datumvrac` FROM `iznajmljivanje` where `kid`='"+knjigaTxt.getText()+"' and ozn='0'";
             pst =  con.prepareStatement(sql);
            pst.execute();
            if(rs.next())
            {
                clanTxt.setText(rs.getString("cid"));
                String datvrac = rs.getString("datumvrac");
                LocalDate danas = LocalDate.now();
                LocalDate vrdan = LocalDate.parse(datvrac);
                
                Long dan_raz = ChronoUnit.DAYS.between(vrdan, danas);
                if(dan_raz>0)
                {
                zakTxt.setText(dan_raz.toString());
                
                long ur = 10*dan_raz;
                urTxt.setText(String.valueOf(ur));
               }
                else{
                    zakTxt.setText("0");
                    urTxt.setText("0");                }
            }
            
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_knjigaTxtKeyReleased

    private void clanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clanTxtActionPerformed

    private void clanTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clanTxtKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clanTxtKeyReleased

    private void zakTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zakTxtActionPerformed

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clanTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField knjigaTxt;
    private javax.swing.JButton spisakBtn;
    private javax.swing.JTextArea spisakTxt;
    private javax.swing.JTextField urTxt;
    private javax.swing.JButton vratiBtn;
    private javax.swing.JTextField zakTxt;
    // End of variables declaration//GEN-END:variables
}
